import Head from "next/head";

import Button from "~/components/Button";
import Link from "next/link";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={'flex items-center justify-center h-screen bg-gray-50'}>
                <div>
                    <div className={'text-6xl text-gray-900 mb-5 font-'}>
                        Welcome<br/>
                        to <span
                        className={"font-extrabold bg-clip-text text-transparent bg-gradient-to-br from-cyan-500 to-violet-600"}>Capital</span>
                    </div>
                    <div className={'text-3xl font-medium text-gray-600 mb-10'}>
                        You personal<br/>
                        savings assistant
                    </div>
                    <div className={"flex justify-center"}>
                        <Link href={'/settings'}>
                            <Button>
                                Let&apos;s start!
                            </Button>
                        </Link>
                    </div>
                </div>

            </main>
        </>
    );
}
